### ISSUE TITLE
[Feature Request] susfs4ksu

### ISSUE THREAD

**Issue by PlatFlat** [TIMISONG-dev/kernel_xiaomi_sm8250#6]
An [addon ](https://gitlab.com/simonpunk/susfs4ksu) root hiding kernel patches and userspace module for KernelSU.
This help prevent mounts and other root related leaks from being detected
Potential help bypass root detector app.

**Comment by TIMISONG-dev** [comment]
Well, I'll think about it

**Comment by PlatFlat** [comment]
@TIMISONG-dev I think adding susfs4ksu to existing KernelSU would be a great addition for hiding root. I hope you will reconsider adding this.

Nowadays banking/financial apps such as Kotak Neo or Bet365 are blocking access to their app if it is rooted phone.

For reference: This is how another dev natsumerinchan, does for oneplus_sm8350:

https://github.com/natsumerinchan/android_kernel_oneplus_sm8350/commit/69b5a59b7548aa8c94f4b836b5ed45fb06e4a88c
https://github.com/natsumerinchan/android_kernel_oneplus_sm8350/commit/89dab19743ac776e421edc76beb0f45e8bc3e0b6
https://github.com/natsumerinchan/android_kernel_oneplus_sm8350/commit/92e72a4e49e15a181c41ab3426f8875f732850e0

Note: Since MagicTime is using 4.19 kernel, you'll need to pick "select 50_add_susfs_in_kernel-4.19.patch" in kernel_patches
folder in susfs4ksu to patch according based on kernel version.

**Comment by TIMISONG-dev** [comment]
Well, I check it later. Thanks

**Comment by TIMISONG-dev** [comment]
I added, but wifi and bluetooth dont work. Maybe i should add some configs? Check my latest commit, maybe u find problem

**Comment by TIMISONG-dev** [comment]
I imported and added all the configs, but there were problems with the network, apparently something broke. Can you check what's wrong?

**Comment by PlatFlat** [comment]
I tested the new build, I didn't experience any network issue for now:

![image](https://github.com/user-attachments/assets/3b65218b-cf74-4dac-bec6-3822f9d059bd)

But KernelSU Zygisk Shamiko module is disabled automatically after installing this build.

Are you using the last KernelSU v0.9.5 kernel commits? Because official repo tag, it states [Non-GKI devices can only stay on version 0.9.5 (the manager can update).](https://github.com/tiann/KernelSU/releases/tag/v1.0.0)

**Comment by TIMISONG-dev** [comment]
yeap i use 0.9.5 but for me wifi and bluetooth didnt work. Weird

**Comment by PlatFlat** [comment]
@TIMISONG-dev Did you manage to fix the wifi and bluetooth issue? 

I realized Zygisk Shamiko module is by default disabled when having susfs4ksu built in. It is intended and you have to use the susfs4ksu module instead. All detector apps seems to pass the checks. 

At the moment I don't have a good kernel building PC to build your kernel and test it. I was thinking maybe if you got the time, could you perhaps fork and modify this https://github.com/silvzr/bootlegger_kernel (which uses Git CI Action to build your kernel) for a separate susfs4ksu build so that It doesn't interfere with your main build then perhaps you could open it for testing. 

I tried building your repo from that fork but unfortunately got some error on my end:

```
../scripts/lld-version.sh: 23: ld.lld: not found
drivers/Kconfig:239: can't open file "drivers/kernelsu/Kconfig"
make[2]: *** [../scripts/kconfig/Makefile:104: alioth_defconfig] Error 1
```
 
Using this Workflow based on your [build.sh](https://github.com/TIMISONG-dev/kernel_xiaomi_sm8250/blob/magictime-new/build.sh)

- Kernel_Git: https://github.com/TIMISONG-dev/kernel_xiaomi_sm8250.git
- Kernel_Branch: magictime-new
- Device_Defconfig: alioth_defconfig
- Common_Defconfig: vendor/xiaomi/sm8250-common.config

**Comment by TIMISONG-dev** [comment]
Ok, I will check it later, bcz now I working for release and stability, maybe I will check it when I start 1.0.8

**Comment by PlatFlat** [comment]
Posting this for awareness. Might not need to build the susfs4ksu ksu module manually. Thanks to sidex15, has provided their own scripts to hide mounted path, etc. - https://github.com/sidex15/ksu_module_susfs

**Comment by TIMISONG-dev** [comment]
This feature added. Try to check

**Comment by PlatFlat** [comment]
> This feature added. Try to check

I have tested it, so far it is working great on my end. 
Thank you for integrating this <3

**Comment by PlatFlat** [comment]
@TIMISONG-dev would you be able to help update susfs4ksu to [v1.5.3](https://gitlab.com/simonpunk/susfs4ksu/-/commit/584a2b0c6df2a6779586b1398747128068fad547) once you have fix pending implementations or are available on your end?

Also would like to know

1. If you're able to get ksu_module_susfs [Revision 11](https://github.com/sidex15/ksu_module_susfs/releases/tag/v1.5.2-R11) working? - after reboot?

2. Any plans to integrate with unofficial KernelSU/KSU Manager. For example, [KernelSU - From blackslashxx] (https://github.com/backslashxx/KernelSU)? Since official KernelSU update for non-gki seems to be completely stopped for quite sometime already. 

Newer unofficial KernelSU have Magic Mount thus existing "_/data/adb/ksu/modules.img_" and "_/data/adb/modules_" need to be removed hence existing modules need to be backup before migrating to Magic Mount - move "_/modules/*_" to "_/modules_update/*_"

**Comment by TIMISONG-dev** [comment]
I implemented stable version of susfs and I'm not going to update it now.

1. No bcz it maybe works for susfs 1.5.2 and upper
2. Nope, bcz I don't think it necessary

Ok, I get it

**Comment by PlatFlat** [comment]
I think I might know why ksu_module_susfs [Revision 11](https://github.com/sidex15/ksu_module_susfs/releases/tag/v1.5.2-R11) didn't work. It checks for "susfs:" via dmesg, ~having this [logs off](https://github.com/TIMISONG-dev/kernel_xiaomi_sm8250/commit/d1643f907ef4bd0f9aa65ba88e3ffa6677cbd400) disable that from appearing in logs.~ See Update 2. 

This line checks for "susfs:" then it creates a file called "susfs_active"

https://github.com/sidex15/ksu_module_susfs/blob/86a5f09c1b5adf034b7168daec6870cec8bc3b64/post-fs-data.sh#L11C1-L11C75

Then upon boot complete, this where it checks if "susfs_active" is in that directory and It is where you see KernelSU report the status:

https://github.com/sidex15/ksu_module_susfs/blob/86a5f09c1b5adf034b7168daec6870cec8bc3b64/boot-completed.sh#L16C1-L17C44

**Update 2:**

So it 

I just changed _[if [ -f $tmpfolder/logs/susfs_active ] ; then ](https://github.com/sidex15/ksu_module_susfs/blob/86a5f09c1b5adf034b7168daec6870cec8bc3b64/boot-completed.sh#L16C1-L16C46)_ to:

`if dmesg | grep -q "susfs:"; then`

It works. Not sure if it is because low log buffer size that it failed to create the file

**Update 3:**

ksu_module_susfs Dev replied:
https://github.com/sidex15/ksu_module_susfs/issues/20#issuecomment-2548366170

**Comment by PlatFlat** [comment]
@TIMISONG-dev would you be able to cherry pick this - https://github.com/backslashxx/msm8953-kernel/commit/54a13f9f771cf51eeda332c4bd9a2dffd1cede80 to hide maps properly from detection

P.S for context, it fix this (For more info: https://nullptr.icu/index.php/archives/182/):

![image](https://github.com/user-attachments/assets/5c9c35c9-c6a5-40d2-ad61-7efd1dfe044c)

**Comment by TIMISONG-dev** [comment]
Ok
